#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("RTIS_Vulcan_MBL.Resource", IsApplication=true)]

namespace RTIS_Vulcan_MBL
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int baterychargelevel = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int baterylevel = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int beeperror = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int blackborder = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int blackborderblue = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int blackbordergreen = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int buttonDisabled = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int chargeaempty = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int chargeafull = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int chargeahalf = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int chargeempty = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int chargefull = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int chargehalf = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int found = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int Icon = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int levelaempty = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int levelafull = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int levelahalf = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int levelempty = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int levelfull = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int levelhalf = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int notfound = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int notfound2 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int roundedbutton = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int roundedbuttonamber = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int roundedbuttongreen = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int roundedbuttonpress = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int roundedbuttonpressred = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int roundedbuttonred = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int RTLogo = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int RTLogoTrans = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int Scrollbar = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int signalhigh = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int signallow = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int signalmedium = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int wifisignal = 2130837539;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050059
			public const int POlist = 2131034201;
			
			// aapt resource value: 0x7f050052
			public const int Text = 2131034194;
			
			// aapt resource value: 0x7f050067
			public const int Transferlist = 2131034215;
			
			// aapt resource value: 0x7f050016
			public const int btnAWTransfer = 2131034134;
			
			// aapt resource value: 0x7f050074
			public const int btnAdd = 2131034228;
			
			// aapt resource value: 0x7f050070
			public const int btnAddSlurry = 2131034224;
			
			// aapt resource value: 0x7f050022
			public const int btnAdditions = 2131034146;
			
			// aapt resource value: 0x7f050027
			public const int btnBack = 2131034151;
			
			// aapt resource value: 0x7f050026
			public const int btnBreakdown = 2131034150;
			
			// aapt resource value: 0x7f05001c
			public const int btnCYCCount = 2131034140;
			
			// aapt resource value: 0x7f050086
			public const int btnCancel = 2131034246;
			
			// aapt resource value: 0x7f050017
			public const int btnCanning = 2131034135;
			
			// aapt resource value: 0x7f050025
			public const int btnCreate = 2131034149;
			
			// aapt resource value: 0x7f050071
			public const int btnDecant = 2131034225;
			
			// aapt resource value: 0x7f050018
			public const int btnDispatch = 2131034136;
			
			// aapt resource value: 0x7f05005a
			public const int btnDone = 2131034202;
			
			// aapt resource value: 0x7f05006f
			public const int btnEnterRec = 2131034223;
			
			// aapt resource value: 0x7f05006e
			public const int btnEnterRem = 2131034222;
			
			// aapt resource value: 0x7f050082
			public const int btnErrorOk = 2131034242;
			
			// aapt resource value: 0x7f050019
			public const int btnFGReceiving = 2131034137;
			
			// aapt resource value: 0x7f050012
			public const int btnFreshSlurry = 2131034130;
			
			// aapt resource value: 0x7f05001f
			public const int btnLogout = 2131034143;
			
			// aapt resource value: 0x7f050021
			public const int btnManufacture = 2131034145;
			
			// aapt resource value: 0x7f05006d
			public const int btnMix = 2131034221;
			
			// aapt resource value: 0x7f050013
			public const int btnMixedSlurry = 2131034131;
			
			// aapt resource value: 0x7f050065
			public const int btnNext = 2131034213;
			
			// aapt resource value: 0x7f05002c
			public const int btnPBack = 2131034156;
			
			// aapt resource value: 0x7f05001b
			public const int btnPalletizing = 2131034139;
			
			// aapt resource value: 0x7f050011
			public const int btnPowderPrep = 2131034129;
			
			// aapt resource value: 0x7f050020
			public const int btnRec = 2131034144;
			
			// aapt resource value: 0x7f050010
			public const int btnReceive = 2131034128;
			
			// aapt resource value: 0x7f050084
			public const int btnReprint = 2131034244;
			
			// aapt resource value: 0x7f05007b
			public const int btnSTBack = 2131034235;
			
			// aapt resource value: 0x7f05007c
			public const int btnSTNext = 2131034236;
			
			// aapt resource value: 0x7f050051
			public const int btnSave = 2131034193;
			
			// aapt resource value: 0x7f050029
			public const int btnScan = 2131034153;
			
			// aapt resource value: 0x7f050028
			public const int btnSelect = 2131034152;
			
			// aapt resource value: 0x7f05001e
			public const int btnSettings = 2131034142;
			
			// aapt resource value: 0x7f050073
			public const int btnSolid = 2131034227;
			
			// aapt resource value: 0x7f050023
			public const int btnSolidity = 2131034147;
			
			// aapt resource value: 0x7f05001a
			public const int btnStockTake = 2131034138;
			
			// aapt resource value: 0x7f050080
			public const int btnSuccessOk = 2131034240;
			
			// aapt resource value: 0x7f050014
			public const int btnToProd = 2131034132;
			
			// aapt resource value: 0x7f050024
			public const int btnTransfer = 2131034148;
			
			// aapt resource value: 0x7f050088
			public const int btnWarningNo = 2131034248;
			
			// aapt resource value: 0x7f050087
			public const int btnWarningYes = 2131034247;
			
			// aapt resource value: 0x7f050015
			public const int btnZectTransfer = 2131034133;
			
			// aapt resource value: 0x7f050072
			public const int btnZonen = 2131034226;
			
			// aapt resource value: 0x7f05003b
			public const int chkAWTrans = 2131034171;
			
			// aapt resource value: 0x7f050040
			public const int chkCYCCount = 2131034176;
			
			// aapt resource value: 0x7f05003c
			public const int chkCanning = 2131034172;
			
			// aapt resource value: 0x7f05003d
			public const int chkDispatch = 2131034173;
			
			// aapt resource value: 0x7f05003e
			public const int chkFGReceiving = 2131034174;
			
			// aapt resource value: 0x7f050037
			public const int chkFreshSlurry = 2131034167;
			
			// aapt resource value: 0x7f050038
			public const int chkMixedSlurry = 2131034168;
			
			// aapt resource value: 0x7f050042
			public const int chkPalletizing = 2131034178;
			
			// aapt resource value: 0x7f050036
			public const int chkPowderPrep = 2131034166;
			
			// aapt resource value: 0x7f050035
			public const int chkReceive = 2131034165;
			
			// aapt resource value: 0x7f05003f
			public const int chkStockTake = 2131034175;
			
			// aapt resource value: 0x7f050039
			public const int chkToProd = 2131034169;
			
			// aapt resource value: 0x7f050041
			public const int chkUserTrack = 2131034177;
			
			// aapt resource value: 0x7f05003a
			public const int chkZectTrans = 2131034170;
			
			// aapt resource value: 0x7f050005
			public const int digitalClock = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int imageView1 = 2131034119;
			
			// aapt resource value: 0x7f050004
			public const int imgBat = 2131034116;
			
			// aapt resource value: 0x7f05007f
			public const int imgError = 2131034239;
			
			// aapt resource value: 0x7f050001
			public const int imgWifi = 2131034113;
			
			// aapt resource value: 0x7f050032
			public const int lblBranch = 2131034162;
			
			// aapt resource value: 0x7f05005e
			public const int lblCode = 2131034206;
			
			// aapt resource value: 0x7f050081
			public const int lblErrorMsg = 2131034241;
			
			// aapt resource value: 0x7f050057
			public const int lblHeader = 2131034199;
			
			// aapt resource value: 0x7f05005b
			public const int lblHeader1 = 2131034203;
			
			// aapt resource value: 0x7f05005c
			public const int lblHeader2 = 2131034204;
			
			// aapt resource value: 0x7f05005f
			public const int lblHeader3 = 2131034207;
			
			// aapt resource value: 0x7f050061
			public const int lblHeader4 = 2131034209;
			
			// aapt resource value: 0x7f050060
			public const int lblLotNumber = 2131034208;
			
			// aapt resource value: 0x7f050083
			public const int lblMainHeader = 2131034243;
			
			// aapt resource value: 0x7f05002a
			public const int lblPass = 2131034154;
			
			// aapt resource value: 0x7f050077
			public const int lblSST = 2131034231;
			
			// aapt resource value: 0x7f05004c
			public const int lblSTSettings = 2131034188;
			
			// aapt resource value: 0x7f050079
			public const int lblSWH = 2131034233;
			
			// aapt resource value: 0x7f050043
			public const int lblScanID = 2131034179;
			
			// aapt resource value: 0x7f050034
			public const int lblScanS = 2131034164;
			
			// aapt resource value: 0x7f050063
			public const int lblSep = 2131034211;
			
			// aapt resource value: 0x7f05002e
			public const int lblServerIP = 2131034158;
			
			// aapt resource value: 0x7f050030
			public const int lblServerPort = 2131034160;
			
			// aapt resource value: 0x7f05007e
			public const int lblSuccessMsg = 2131034238;
			
			// aapt resource value: 0x7f050047
			public const int lblToProd = 2131034183;
			
			// aapt resource value: 0x7f050002
			public const int lblVersion = 2131034114;
			
			// aapt resource value: 0x7f050009
			public const int lbllogin = 2131034121;
			
			// aapt resource value: 0x7f05007d
			public const int linearLayout10 = 2131034237;
			
			// aapt resource value: 0x7f050006
			public const int linearLayout2 = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int linearLayout3 = 2131034120;
			
			// aapt resource value: 0x7f05001d
			public const int linearLayout4 = 2131034141;
			
			// aapt resource value: 0x7f05002d
			public const int linearLayout5 = 2131034157;
			
			// aapt resource value: 0x7f050003
			public const int linearLayoutBatTime = 2131034115;
			
			// aapt resource value: 0x7f05000c
			public const int linearLayoutButton1 = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int linearLayoutButton2 = 2131034125;
			
			// aapt resource value: 0x7f05000f
			public const int linearLayoutButton3 = 2131034127;
			
			// aapt resource value: 0x7f05000b
			public const int linearLayoutImage = 2131034123;
			
			// aapt resource value: 0x7f050000
			public const int linearLayoutMenu = 2131034112;
			
			// aapt resource value: 0x7f05004e
			public const int radDouble = 2131034190;
			
			// aapt resource value: 0x7f05004f
			public const int radRecount = 2131034191;
			
			// aapt resource value: 0x7f05004d
			public const int radSingle = 2131034189;
			
			// aapt resource value: 0x7f05000e
			public const int scrollView1 = 2131034126;
			
			// aapt resource value: 0x7f050078
			public const int spnStockTake = 2131034232;
			
			// aapt resource value: 0x7f05007a
			public const int spnWarehouse = 2131034234;
			
			// aapt resource value: 0x7f050075
			public const int spnWhses = 2131034229;
			
			// aapt resource value: 0x7f05004a
			public const int txtAWWhse = 2131034186;
			
			// aapt resource value: 0x7f050066
			public const int txtBCD = 2131034214;
			
			// aapt resource value: 0x7f050085
			public const int txtBarcode = 2131034245;
			
			// aapt resource value: 0x7f050033
			public const int txtBranch = 2131034163;
			
			// aapt resource value: 0x7f05004b
			public const int txtCanWhse = 2131034187;
			
			// aapt resource value: 0x7f05006c
			public const int txtChemical = 2131034220;
			
			// aapt resource value: 0x7f050055
			public const int txtDesc = 2131034197;
			
			// aapt resource value: 0x7f050045
			public const int txtFStMS = 2131034181;
			
			// aapt resource value: 0x7f050058
			public const int txtItem = 2131034200;
			
			// aapt resource value: 0x7f050054
			public const int txtItemLot = 2131034196;
			
			// aapt resource value: 0x7f050053
			public const int txtItemNo = 2131034195;
			
			// aapt resource value: 0x7f05000a
			public const int txtLogin = 2131034122;
			
			// aapt resource value: 0x7f050068
			public const int txtLot = 2131034216;
			
			// aapt resource value: 0x7f050046
			public const int txtMStZect = 2131034182;
			
			// aapt resource value: 0x7f05005d
			public const int txtOrder = 2131034205;
			
			// aapt resource value: 0x7f050044
			public const int txtPPtFS = 2131034180;
			
			// aapt resource value: 0x7f05002b
			public const int txtPassword = 2131034155;
			
			// aapt resource value: 0x7f050056
			public const int txtQty = 2131034198;
			
			// aapt resource value: 0x7f050062
			public const int txtQty1 = 2131034210;
			
			// aapt resource value: 0x7f050064
			public const int txtQty2 = 2131034212;
			
			// aapt resource value: 0x7f050076
			public const int txtScanItem = 2131034230;
			
			// aapt resource value: 0x7f050050
			public const int txtScannerID = 2131034192;
			
			// aapt resource value: 0x7f05002f
			public const int txtServerIP = 2131034159;
			
			// aapt resource value: 0x7f050031
			public const int txtServerPort = 2131034161;
			
			// aapt resource value: 0x7f05006b
			public const int txtTank = 2131034219;
			
			// aapt resource value: 0x7f050048
			public const int txtToProd = 2131034184;
			
			// aapt resource value: 0x7f050069
			public const int txtWeight1 = 2131034217;
			
			// aapt resource value: 0x7f05006a
			public const int txtWeight2 = 2131034218;
			
			// aapt resource value: 0x7f050049
			public const int txtZectWhse = 2131034185;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int A_Login = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int B_Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int B_Sub_Menu = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int B_Sub_Menu_2 = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int C_EnterPassword = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int C_RTSettings = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int D_ListViewItem = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int D_ScanItem = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int D_ScanPO = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int E_Confirm_Rec_Trans = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int E_Scan_Dry_Weight = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int E_Scan_Slurry_BCD = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int E_SelectItem = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int F_G_EnterLot = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int F_G_EnterWeight = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int F_G_Scan_Slurry_Tank = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int G_ChemicalItem = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int G_Sub_Menu = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int G_ViewSlurries = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int H_Scan_Dry_Weight = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int H_Scan_Slurry_BCD = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int H_Scan_Slurry_Tank = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int H_SelectWhse = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int I_ScanItem = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int J_SelectST = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int Q_ScanItem = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int SuccessMsg = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int Z_ErrorMsg = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int Z_Success = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int Z_Warning = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public const int Z_YesNo = 2130903070;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
